### ISSUE TITLE
Error while encoding no matter what options

### ISSUE THREAD

**Issue by cacafuti8888** [Kidsnd274/Av1anStaxRipWrapper#3]
WARN [av1an_core::broker] Encoder failed (on chunk 0):
encoder crashed: exit code: 2
stdout:

stderr:
        error: Found argument '--photon-noise-table' which wasn't expected, or isn't valid in this context

                If you tried to supply `--photon-noise-table` as a value rather than a flag, use `-- --photon-noise-table`

**Comment by Kidsnd274** [comment]
What's the full command that you gave StaxRip?

**Comment by cacafuti8888** [comment]
Hi, i put several commands including the default you provide `"%startup_dir%\Apps\Encoders\Av1anStaxRipWrapper\VapourSynth\python.exe" "%startup_dir%\Apps\Encoders\Av1anStaxRipWrapper\Av1anStaxRipWrapper.py" -s "%startup_dir%" -i "%source_file%" -o "%encoder_out_file%" -t "%temp_dir%av1an_temp" --pix-format yuv420p10le -e rav1e --photon-noise 2 --chroma-noise --sc-downscale-height 540 -v "--quantizer 60 --speed 6 --tiles 2 --threads 2"`

`"%startup_dir%\Apps\Encoders\Av1anStaxRipWrapper\VapourSynth\python.exe" "%startup_dir%\Apps\Encoders\Av1anStaxRipWrapper\Av1anStaxRipWrapper.py" -s "%startup_dir%" -i "%source_file%" -o "%encoder_out_file%" -t "%temp_dir%av1an_temp" --pix-format yuv420p10le -e rav1e -v "--quantizer 60 --speed 6 --tiles 2 --threads 2"`

And even tried setting different encoder (aom) with the same result. Also deleted the "--photon-noise 2 --chroma-noise" strings but i keep getting the same error.

**Comment by Kidsnd274** [comment]
Hmm that's weird. I will give it a try when I have time. Maybe there's a bug in the script. Meanwhile, can you try following the steps exactly in this video to see if it fixes the issue?

https://youtu.be/a7IPQcNVwTY

Also delete the av1an_temp folder for each job when retrying.

**Comment by Kidsnd274** [comment]
Hi, I know it's been a while. Does this error still happen with the latest commit? I have just tested the two commands you gave above and they both work fine.
